# Generated by Django 5.0.7 on 2024-07-21 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archimed', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='investor',
            name='payment_type',
            field=models.CharField(choices=[('upfront', 'Upfront'), ('yearly', 'Yearly')], default='yearly', max_length=10),
        ),
    ]
