# Generated by Django 5.0.7 on 2024-07-21 20:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archimed', '0003_bill'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='bill_code',
            field=models.CharField(default='default_bill_code', max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bill',
            name='issue_date',
            field=models.DateField(default=datetime.date(2024, 7, 21)),
            preserve_default=False,
        ),
    ]
