# Generated by Django 5.0.7 on 2024-07-22 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archimed', '0004_bill_bill_code_bill_issue_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('fee_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('iban', models.CharField(max_length=34)),
            ],
        ),
    ]
