# Generated by Django 5.0.7 on 2024-07-22 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archimed', '0006_remove_company_fee_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='fee_percentage',
            field=models.DecimalField(decimal_places=2, default=0.02, max_digits=5),
            preserve_default=False,
        ),
    ]
