# Generated by Django 5.0.7 on 2024-07-23 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archimed', '0007_company_fee_percentage'),
    ]

    operations = [
        migrations.CreateModel(
            name='CapitalCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('company_iban', models.CharField(max_length=34)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('date', models.DateField(auto_now_add=True)),
                ('due_date', models.DateField()),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('validated', 'Validated'), ('sent', 'Sent'), ('paid', 'Paid'), ('overdue', 'Overdue')], default='sent', max_length=10)),
            ],
        ),
    ]
